apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/jankul02/argoapplicationset.git
        revision: HEAD
        files:
        - path: "git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: '{{repo.url}}'
        targetRevision: HEAD
        path: "git-generator-files-discovery/apps"
        helm:
          parameters:
          - name: "destNamespace"
            value: 'guestbook-{{cluster.name}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: 'guestbook'
